#
# FICHIER DE PROPRIETES
#

# CONF DB
jdbc.driver.class=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/gestbook
jdbc.login=root
jdbc.password=root

# pepers
password.pepper="Mieux vaut vivre un jour comme un lion que cent ans comme un mouton"